# -*- coding: utf-8 -*-
"""Rnn_Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgYNgJaktOZUVIDIlM1uJ6vg8qeBjNXw
"""

import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing import sequence

# 1. Hyperparameters and configuration
MAX_FEATURES = 10000  # Number of top most frequent words to consider
MAX_LEN = 100        # Maximum length of each review sequence
BATCH_SIZE = 32
EPOCHS = 5

# 2. Load the built-in IMDb dataset
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=MAX_FEATURES)

# 3. Pad sequences to ensure uniform input length
x_train = sequence.pad_sequences(x_train, maxlen=MAX_LEN)
x_test = sequence.pad_sequences(x_test, maxlen=MAX_LEN)

x_train

# 4. Build the RNN Architecture
model = Sequential([
    # Embedding layer maps word integer indices into dense vectors of shape (batch, 100, 32)
    Embedding(input_dim=MAX_FEATURES, output_dim=32, input_length=MAX_LEN),

    # SimpleRNN layer with 64 hidden units
    SimpleRNN(units=64, activation='tanh'),

    # Dense output layer for binary classification
    Dense(units=1, activation='sigmoid')
])

# 5. Compile the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 6. Train the model
history = model.fit(
    x_train, y_train,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    validation_split=0.2
)

# Display model architecture summary
model.summary()

# 7. Evaluate on test data
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_acc * 100:.2f}%")

import numpy as np
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence

word_index = imdb.get_word_index()

def predict_custom_review(review_text, model, max_features=10000, max_len=100):
    words = review_text.lower().split()
    encoded_review = []
    for word in words:
        index = word_index.get(word, None)
        if index is not None and (index + 3) < max_features:
            encoded_review.append(index + 3)
        else:
            encoded_review.append(2)  #(Out-of-vocabulary)

    padded_review = sequence.pad_sequences([encoded_review], maxlen=max_len)

    prediction = model.predict(padded_review, verbose=0)[0][0]

    sentiment = "Positive Review" if prediction >= 0.5 else "Negative Review (బాగాలేదు / నెగటివ్)"
    confidence = prediction if prediction >= 0.5 else (1 - prediction)

    print(f"\nReview: '{review_text}'")
    print(f"Prediction Score: {prediction:.4f}")
    print(f"Result: {sentiment} (Confidence: {confidence * 100:.2f}%)")

sample_positive = "The movie was wonderful and the acting was brilliant"
sample_negative = "This movie is terrible and the story is totally boring"

predict_custom_review(sample_positive, model)

predict_custom_review(sample_negative, model)

import re
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, SpatialDropout1D
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.callbacks import EarlyStopping

# 1. Hyperparameters configuration
MAX_FEATURES = 10000   # Vocabulary size: Top 10,000 most frequent words
MAX_LEN = 150          # Maximum length of each review sequence
EMBEDDING_DIM = 64     # Dimension of the dense embedding vector
BATCH_SIZE = 64        # Number of samples per gradient update
EPOCHS = 10            # Maximum number of training epochs

# 2. Dataset Loading & Padding
# Load pre-tokenized IMDb movie review dataset
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=MAX_FEATURES)

# Pad sequences with zeros or truncate to ensure uniform length (MAX_LEN)
x_train = sequence.pad_sequences(x_train, maxlen=MAX_LEN)
x_test = sequence.pad_sequences(x_test, maxlen=MAX_LEN)

# 3. Model Architecture Construction
model = Sequential([
    # Convert integer indices to dense vectors of fixed size
    Embedding(input_dim=MAX_FEATURES, output_dim=EMBEDDING_DIM),

    # 1D Spatial Dropout drops entire 1D feature maps along word dimensions to prevent overfitting
    SpatialDropout1D(0.2),

    # Bidirectional LSTM processes the input sequence in both forward and backward directions
    Bidirectional(LSTM(units=64, dropout=0.2, recurrent_dropout=0.2)),

    # Fully connected hidden layer with ReLU activation
    Dense(units=32, activation='relu'),

    # Standard Dropout to further regularize the model
    Dropout(0.3),

    # Output layer: Sigmoid activation outputs a probability value between 0 and 1
    Dense(units=1, activation='sigmoid')
])

# 4. Compile the Model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 5. Early Stopping Callback
# Monitors validation loss and stops training if no improvement is seen for 2 consecutive epochs
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True,
    verbose=1
)

# 6. Train the Model
history = model.fit(
    x_train, y_train,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    validation_split=0.2,
    callbacks=[early_stop]
)

# 7. Inference Pipeline for Custom Reviews
# Retrieve the word-to-index mapping dictionary from the IMDb dataset
word_index = imdb.get_word_index()

def predict_review(text):
    # Remove punctuation, special characters, and convert text to lowercase
    clean_text = re.sub(r'[^a-zA-Z0-9\s]', '', text.lower())
    words = clean_text.split()

    # Apply standard IMDb index offset (+3 reserved for padding, start char, and unknown tokens)
    encoded = [
        word_index.get(w, 2) + 3 if (word_index.get(w, 2) + 3) < MAX_FEATURES else 2
        for w in words
    ]

    # Pad input sequence to match expected model input shape
    padded = sequence.pad_sequences([encoded], maxlen=MAX_LEN)

    # Predict output probability
    prob = model.predict(padded, verbose=0)[0][0]
    label = "Positive" if prob >= 0.5 else "Negative"
    confidence = prob if prob >= 0.5 else (1 - prob)

    print(f"Review: '{text}'")
    print(f"Prediction: {label} (Score: {prob:.4f} | Confidence: {confidence * 100:.2f}%)\n")

# Testing the model with sample reviews
predict_review("The movie was wonderful and the acting was brilliant")
predict_review("This movie is terrible and the story is totally boring")
predict_review("Not good, absolute waste of time and money")